## Datacamp
### Introduction to Numpy
#### Selecting and Updating Data
Kadriye Tuba Türkcan Karaca

## Slicing and indexing trees
Imagine we are working with data from New York City's tree census. Each row of the tree_census 2D  lists information for a different tree: the tree ID, block ID, trunk diameter, and stump diameter in that order. Living trees do not have stump diameters, which explains why there are so many zeros in that column. Column order is important because NumPy does not have column names! 

We'll be working specifically with the second column, representing block IDs: our research requires us to select specific city blocks for further analysis using NumPy slicing and indexing. 

In [4]:
import numpy as np

In [3]:
tree_census_list = [[     3, 501451,     24,      0], [     4, 501451,     20,      0], [     7, 501911,      3,      0], [     8, 501911,      3,      0], [     9, 501911,      4,      0], [    10, 501911,      4,      0], [    11, 501911,      4,      0], [    12, 501911,      4,      0], [    13, 501911,      4,      0], [    14, 501911,      3,      0], [    15, 501911,      3,      0], [    16, 501911,      4,      0], [    17, 501909,      2,      0], [    18, 501909,      2,      0], [    19, 501909,      3,      0], [    20, 501909,      4,      0], [    21, 501909,      4,      0], [    22, 501909,      4,      0], [    23, 501909,      0,      3], [    26, 501967,     14,      0], [    27, 501967,      3,      0], [    28, 501967,      4,      0], [    29, 501134,      7,      0], [    30, 501134,      8,      0], [    31, 501134,      7,      0], [    32, 501134,      8,      0], [    33, 501134,      7,      0], [    34, 501134,      5,      0], [    35, 501134,      6,      0], [    36, 501134,      5,      0], [    37, 501966,      5,      0], [    38, 501966,     17,      0], [    39, 501966,      0,     31], [    40, 501966,     19,      0], [    41, 501966,     21,      0], [    42, 501966,     18,      0], [    43, 500846,      4,      0], [    44, 500846,      5,      0], [    45, 500846,      3,      0], [    46, 500846,      4,      0], [    47, 500846,      3,      0], [    48, 500846,      4,      0], [    49, 500836,     13,      0], [    50, 500836,     13,      0], [    51, 500836,     13,      0], [    52, 500836,      5,      0], [    53, 500836,      4,      0], [    54, 500836,      4,      0], [    55, 500836,      4,      0], [    56, 500836,     11,      0], [    57, 500836,      5,      0], [    58, 500836,      4,      0], [    59, 500836,      5,      0], [    60, 501882,      8,      0], [    61, 501882,     51,      0], [    62, 501882,      7,      0], [    63, 501882,      4,      0], [    64, 501882,     15,      0], [    65, 501882,      3,      0], [    66, 501882,      8,      0], [    67, 501882,      6,      0], [    68, 501882,      6,      0], [    69, 501882,      3,      0], [    70, 501113,      4,      0], [    71, 501113,      3,      0], [    72, 501113,      2,      0], [    73, 501113,      3,      0], [    74, 501113,      3,      0], [    75, 500917,      6,      0], [    76, 500917,      5,      0], [    77, 500917,      5,      0], [    85, 501323,      5,      0], [    86, 501323,      5,      0], [    87, 501323,      9,      0], [    88, 501323,      4,      0], [    89, 501323,      4,      0], [    90, 501323,      7,      0], [    91, 501323,      7,      0], [   113, 501451,      6,      0], [   114, 501451,      5,      0], [   115, 516296,      4,      0], [   116, 516296,      4,      0], [   117, 516296,      5,      0], [   118, 516296,      5,      0], [   119, 516296,      5,      0], [   120, 516296,      7,      0], [   121, 516296,      3,      0], [   122, 516296,      5,      0], [   123, 516296,      3,      0], [   124, 516296,      3,      0], [   125, 516296,      6,      0], [   126, 516296,      6,      0], [   127, 516296,      8,      0], [   128, 516296,      7,      0], [   129, 503178,      4,      0], [   130, 503178,      5,      0], [   131, 503178,      4,      0], [   132, 503178,      4,      0], [   133, 503178,      4,      0], [   134, 503178,      4,      0], [   135, 501451,      6,      0], [   136, 501451,      5,      0], [   137, 501451,      3,      0], [   138, 501451,      4,      0], [   139, 501451,     12,      0], [   140, 501451,     12,      0], [   141, 501451,     12,      0], [   142, 501451,      5,      0], [   143, 501451,      6,      0], [   144, 501874,      6,      0], [   145, 501874,      6,      0], [   146, 501874,      6,      0], [   147, 501874,      6,      0], [   148, 501874,      5,      0], [   149, 501874,      5,      0], [   150, 501874,      6,      0], [   151, 501874,      7,      0], [   152, 501874,      7,      0], [   153, 501874,     25,      0], [   154, 501874,      0,      5], [   155, 501874,      5,      0], [   156, 501874,      4,      0], [   157, 501874,      6,      0], [   158, 501874,      6,      0], [   159, 501874,      7,      0], [   160, 501874,     11,      0], [   161, 501874,      6,      0], [   162, 501874,     17,      0], [   163, 501874,     13,      0], [   164, 501874,     14,      0], [   165, 501874,     14,      0], [   166, 501874,     20,      0], [   167, 501874,     15,      0], [   168, 501874,     13,      0], [   169, 501874,      7,      0], [   170, 501874,      7,      0], [   171, 501874,     10,      0], [   172, 501874,     17,      0], [   173, 501874,     14,      0], [   174, 501874,      4,      0], [   175, 501874,      6,      0], [   176, 501874,      7,      0], [   177, 501874,      8,      0], [   178, 501874,      7,      0], [   179, 501874,      7,      0], [   180, 501874,      6,      0], [   181, 501874,      7,      0], [   182, 501874,      5,      0], [   183, 501942,      2,      0], [   184, 501942,      2,      0], [   185, 501942,      2,      0], [   186, 501942,      2,      0], [   187, 314009,     26,      0], [   188, 314009,     25,      0], [   189, 314009,      2,      0], [   190, 314009,     15,      0], [   191, 314009,      6,      0], [   192, 314009,     20,      0], [   193, 314009,      5,      0], [   194, 314009,      9,      0], [   195, 314009,     15,      0], [   196, 314009,     13,      0], [   197, 314009,     15,      0], [   198, 314009,      3,      0], [   199, 314009,      2,      0], [   200, 314009,     13,      0], [   201, 314009,      6,      0], [   202, 314009,     12,      0], [   203, 314009,     15,      0], [   204, 314009,     18,      0], [   205, 314009,     22,      0], [   206, 314009,     18,      0], [   207, 314009,     18,      0], [   208, 314009,     15,      0], [   209, 314009,     17,      0], [   210, 501867,      7,      0], [   211, 501867,      3,      0], [   212, 501841,      7,      0], [   213, 501841,      8,      0], [   214, 501841,      4,      0], [   215, 501892,     12,      0], [   216, 501892,     11,      0], [   217, 501892,     12,      0], [   218, 501892,      3,      0], [   219, 501892,      9,      0], [   220, 501892,     12,      0], [   221, 501892,     11,      0], [   222, 501892,     10,      0], [   223, 501892,      8,      0], [   224, 501892,      6,      0], [   225, 501892,      6,      0], [   226, 501892,      7,      0], [   227, 501892,      7,      0], [   228, 501892,      3,      0], [   229, 501892,     15,      0], [   230, 501892,     12,      0], [   231, 501892,      0,     12], [   232, 501892,      4,      0], [   305, 501897,      5,      0], [   306, 501897,      5,      0], [   307, 501897,      5,      0], [   308, 501897,      4,      0], [   309, 501897,      4,      0], [   310, 501897,      5,      0], [   311, 501897,      4,      0], [   312, 501897,      9,      0], [   313, 501897,      2,      0], [   314, 501897,      4,      0], [   315, 501897,      4,      0], [   316, 501897,      6,      0], [   317, 501897,      5,      0], [   318, 501897,      5,      0], [   319, 501897,      2,      0], [   320, 501897,      5,      0], [   321, 501897,      5,      0], [   322, 501897,      4,      0], [   323, 501897,      4,      0], [   324, 501897,      5,      0], [   325, 501897,      5,      0], [   344, 501893,      6,      0], [   345, 501893,     11,      0], [   346, 501893,      4,      0], [   347, 501893,      5,      0], [   348, 501893,      0,      7], [   349, 501893,      3,      0], [   350, 501893,     14,      0], [   351, 501893,     11,      0], [   352, 501893,     10,      0], [   353, 501893,      7,      0], [   354, 501893,     15,      0], [   355, 501893,     10,      0], [   356, 107255,      5,      0], [   357, 107255,      6,      0], [   358, 107255,     10,      0], [   359, 107255,     10,      0], [   360, 413051,      6,      0], [   361, 413051,      5,      0], [   362, 413051,      4,      0], [   363, 413051,      4,      0], [   364, 413051,      3,      0], [   365, 413051,      5,      0], [   366, 413051,      4,      0], [   367, 413051,     14,      0], [   368, 413051,     12,      0], [   369, 413051,     11,      0], [   370, 413051,      8,      0], [   371, 413051,     14,      0], [   372, 413051,     12,      0], [   373, 413051,      9,      0], [   374, 413051,     12,      0], [   375, 413051,     11,      0], [   376, 413051,      7,      0], [   377, 413051,      8,      0], [   378, 413051,     10,      0], [   379, 413051,     10,      0], [   380, 413051,     12,      0], [   381, 413051,     11,      0], [   382, 413051,     12,      0], [   383, 413051,      5,      0], [   384, 413051,      5,      0], [   385, 413051,      6,      0], [   386, 413052,      0,      9], [   387, 413052,      0,      9], [   388, 413052,      8,      0], [   389, 413052,      5,      0], [   390, 413052,      5,      0], [   391, 413052,      5,      0], [   392, 413052,      6,      0], [   393, 413052,      6,      0], [   394, 107288,     12,      0], [   395, 107288,     12,      0], [   396, 107288,     11,      0], [   397, 413086,     12,      0], [   398, 413086,      8,      0], [   399, 413086,      9,      0], [   400, 413086,      5,      0], [   401, 413086,      5,      0], [   402, 413086,      5,      0], [   403, 413086,      0,      8], [   404, 413086,      2,      0], [   405, 413086,      2,      0], [   406, 413086,      2,      0], [   407, 207803,     14,      0], [   408, 207803,      0,     18], [   409, 207803,     14,      0], [   410, 207803,     14,      0], [   411, 207803,     22,      0], [   412, 207803,     15,      0], [   413, 207803,     19,      0], [   414, 207803,     14,      0], [   415, 207803,     18,      0], [   419, 107278,      7,      0], [   420, 107278,      7,      0], [   421, 107278,      7,      0], [   422, 107188,      8,      0], [   423, 107188,      8,      0], [   424, 107188,      5,      0], [   425, 107188,     10,      0], [   426, 107188,     14,      0], [   427, 207088,      2,      0], [   428, 207088,      2,      0], [   429, 207088,      2,      0], [   430, 207088,      2,      0], [   431, 107256,     11,      0], [   432, 107256,     12,      0], [   433, 107256,     12,      0], [   434, 207945,      3,      0], [   435, 207945,      3,      0], [   436, 207945,      3,      0], [   437, 207945,      3,      0], [   438, 207945,      3,      0], [   439, 207112,      6,      0], [   440, 207112,      6,      0], [   441, 207112,      8,      0], [   442, 507568,      2,      0], [   443, 507568,      2,      0], [   444, 507568,     11,      0], [   445, 107277,     11,      0], [   446, 107277,     11,      0], [   447, 107277,      9,      0], [   448, 107277,     11,      0], [   449, 107277,     12,      0], [   450, 107277,     13,      0], [   451, 107277,      9,      0], [   452, 107277,     11,      0], [   453, 107285,      6,      0], [   454, 107285,      0,      4], [   455, 107285,      5,      0], [   456, 107285,      5,      0], [   457, 207802,      2,      0], [   458, 207802,      2,      0], [   459, 207802,      8,      0], [   460, 207041,     10,      0], [   461, 207041,      0,      7], [   462, 207041,      0,      9], [   463, 207041,      0,     11], [   464, 207041,      0,     11], [   465, 516271,      1,      0], [   466, 516271,      2,      0], [   467, 516271,     26,      0], [   468, 516271,      4,      0], [   469, 516271,     13,      0], [   470, 516271,      2,      0], [   471, 207199,      4,      0], [   472, 207199,      3,      0], [   473, 207199,      4,      0], [   474, 207199,      4,      0], [   475, 207199,      4,      0], [   476, 207199,      4,      0], [   477, 207199,      0,      3], [   478, 207199,      4,      0], [   479, 207199,      2,      0], [   480, 207199,      2,      0], [   481, 507598,     12,      0], [   482, 507598,     13,      0], [   483, 207201,      5,      0], [   484, 207201,      4,      0], [   485, 507613,      2,      0], [   486, 507613,      3,      0], [   487, 507613,      3,      0], [   488, 507613,     25,      0], [   489, 507599,     11,      0], [   490, 507599,     11,      0], [   491, 507599,     14,      0], [   492, 507599,     22,      0], [   493, 507599,      2,      0], [   494, 507599,      3,      0], [   495, 507599,     10,      0], [   496, 507599,      2,      0], [   497, 507599,      2,      0], [   498, 507599,     13,      0], [   499, 207200,     19,      0], [   500, 207200,     26,      0], [   501, 207200,     21,      0], [   502, 207200,     19,      0], [   503, 207200,     14,      0], [   504, 207200,     14,      0], [   505, 207200,      5,      0], [   506, 207200,     19,      0], [   507, 207200,     15,      0], [   508, 207200,      0,     11], [   509, 207200,      0,     15], [   510, 207200,      0,      6], [   511, 207200,     19,      0], [   514, 507614,     17,      0], [   515, 507614,     12,      0], [   516, 507539,     13,      0], [   517, 507539,     15,      0], [   518, 507539,     12,      0], [   519, 507539,      2,      0], [   520, 507539,     16,      0], [   521, 507539,      2,      0], [   529, 507615,      2,      0], [   530, 507615,      2,      0], [   531, 507615,     25,      0], [   532, 507615,      2,      0], [   533, 507615,     21,      0], [   534, 507615,      2,      0], [   535, 343368,     15,      0], [   536, 343368,     16,      0], [   537, 349684,     14,      0], [   538, 349684,     13,      0], [   539, 349684,     11,      0], [   540, 349687,      8,      0], [   541, 349687,     11,      0], [   542, 349687,     13,      0], [   543, 349687,     12,      0], [   544, 342452,      7,      0], [   545, 342452,     24,      0], [   546, 342452,     19,      0], [   547, 342452,      3,      0], [   548, 342453,      3,      0], [   549, 342453,      4,      0], [   550, 342453,      6,      0], [   551, 342453,     11,      0], [   552, 344023,     17,      0], [   553, 344023,     19,      0], [   554, 344023,     19,      0], [   555, 344023,     17,      0], [   556, 344023,     15,      0], [   557, 344023,     13,      0], [   558, 344023,     15,      0], [   559, 342454,      0,     27], [   560, 342454,     16,      0], [   561, 342454,     15,      0], [   562, 342454,      0,     20], [   563, 342454,     17,      0], [   564, 342454,     16,      0], [   565, 349688,      4,      0], [   566, 349688,     10,      0], [   567, 349688,      9,      0], [   568, 349688,     14,      0], [   569, 349688,     11,      0], [   570, 349688,     12,      0], [   571, 349688,      8,      0], [   572, 349688,      9,      0], [   573, 349688,      9,      0], [   574, 349688,     13,      0], [   575, 349688,     14,      0], [   576, 349688,      7,      0], [   577, 349688,     11,      0], [   578, 349688,     14,      0], [   579, 349688,      3,      0], [   580, 349688,      7,      0], [   587, 342455,     16,      0], [   588, 342455,     17,      0], [   589, 342455,     13,      0], [   590, 342455,     14,      0], [   591, 342455,     16,      0], [   592, 342456,     12,      0], [   593, 342456,      4,      0], [   594, 342457,      5,      0], [   595, 342457,      3,      0], [   596, 342457,     16,      0], [   597, 342457,     11,      0], [   598, 342457,      9,      0], [   599, 342457,      9,      0], [   604, 324495,     10,      0], [   605, 324495,      8,      0], [   606, 324495,     10,      0], [   607, 324495,     11,      0], [   608, 324495,     11,      0], [   609, 324495,      8,      0], [   610, 324495,     11,      0], [   611, 324495,     11,      0], [   612, 324495,     11,      0], [   613, 324495,      9,      0], [   614, 324495,     11,      0], [   615, 324495,     10,      0], [   616, 324495,      9,      0], [   617, 324495,      5,      0], [   618, 324495,     12,      0], [   619, 324495,     11,      0], [   620, 324495,     13,      0], [   621, 324495,      9,      0], [   622, 324495,     15,      0], [   623, 324495,     16,      0], [   624, 324495,     12,      0], [   625, 324495,      7,      0], [   626, 342458,     10,      0], [   627, 342458,      6,      0], [   628, 342458,      9,      0], [   629, 342458,      5,      0], [   630, 342458,      9,      0], [   631, 342458,      6,      0], [   632, 342458,      6,      0], [   633, 400788,      3,      0], [   634, 400788,      3,      0], [   635, 400788,      5,      0], [   636, 400788,      4,      0], [   637, 400788,      4,      0], [   638, 400788,      4,      0], [   639, 400788,      4,      0], [   640, 400788,      6,      0], [   641, 400788,      4,      0], [   642, 400788,      7,      0], [   643, 400788,      6,      0], [   644, 400788,      7,      0], [   645, 400787,      6,      0], [   646, 400787,      5,      0], [   647, 400787,      7,      0], [   648, 400787,      8,      0], [   649, 400787,     20,      0], [   650, 400787,      9,      0], [   651, 400787,     11,      0], [   652, 400787,     11,      0], [   653, 400787,     10,      0], [   654, 400787,      9,      0], [   655, 400787,     11,      0], [   656, 400787,     12,      0], [   657, 400787,     10,      0], [   658, 344037,     18,      0], [   659, 344037,      7,      0], [   660, 344037,      4,      0], [   661, 344037,      4,      0], [   662, 344037,      4,      0], [   663, 344037,      4,      0], [   664, 344037,      3,      0], [   665, 344037,     19,      0], [   666, 344037,     12,      0], [   667, 400789,      3,      0], [   668, 400789,      4,      0], [   669, 400789,      5,      0], [   670, 400789,      4,      0], [   671, 400789,      4,      0], [   672, 400789,     17,      0], [   673, 400789,     15,      0], [   674, 400789,      8,      0], [   675, 324274,      4,      0], [   676, 324274,      5,      0], [   677, 324274,      6,      0], [   678, 324274,     25,      0], [   679, 324274,      6,      0], [   680, 344033,     11,      0], [   681, 344033,      3,      0], [   682, 344033,      3,      0], [   683, 344033,     15,      0], [   684, 344033,      4,      0], [   685, 324275,     14,      0], [   686, 324275,     12,      0], [   687, 324275,     15,      0], [   688, 344034,      2,      0], [   689, 344034,      3,      0], [   690, 344034,      2,      0], [   691, 324346,     11,      0], [   692, 324346,     11,      0], [   693, 324346,     14,      0], [   694, 324346,     12,      0], [   695, 324346,     15,      0], [   696, 506799,     12,      0], [   697, 506799,      8,      0], [   698, 506799,      9,      0], [   699, 506799,      9,      0], [   700, 506799,      8,      0], [   701, 506799,      7,      0], [   702, 506799,     12,      0], [   703, 506799,     15,      0], [   704, 506799,      4,      0], [   705, 506799,     11,      0], [   706, 506799,      0,     10], [   707, 330413,      6,      0], [   708, 330413,      7,      0], [   709, 330413,      9,      0], [   710, 330413,     38,      0], [   711, 330413,      6,      0], [   712, 330413,      3,      0], [   713, 324345,     15,      0], [   714, 324345,     11,      0], [   715, 324345,      5,      0], [   716, 324345,      4,      0], [   717, 506834,      2,      0], [   718, 506834,     13,      0], [   719, 506834,     21,      0], [   720, 506834,     26,      0], [   721, 506834,      4,      0], [   722, 342451,     18,      0], [   723, 342451,     10,      0], [   724, 342451,     17,      0], [   725, 342451,     20,      0], [   726, 342451,     19,      0], [   727, 342449,     21,      0], [   728, 342449,     19,      0], [   729, 342449,     18,      0], [   730, 342449,     18,      0], [   731, 342449,     17,      0], [   732, 342447,     24,      0], [   733, 342447,     27,      0], [   734, 342447,     22,      0], [   735, 342447,     21,      0], [   736, 342447,      9,      0], [   737, 342450,     17,      0], [   738, 342450,     17,      0], [   739, 342450,     19,      0], [   740, 342450,     28,      0], [   741, 342450,     21,      0], [   747, 342448,     11,      0], [   748, 342448,     23,      0], [   749, 342448,     28,      0], [   750, 342448,      7,      0], [   751, 342448,     33,      0], [   752, 342446,     30,      0], [   753, 342446,      5,      0], [   754, 342446,     26,      0], [   755, 342446,     27,      0], [   756, 342446,     22,      0], [   757, 506915,      2,      0], [   758, 506915,      2,      0], [   759, 506894,      2,      0], [   760, 506894,      3,      0], [   761, 506894,      4,      0], [   762, 506894,      3,      0], [   763, 507002,      3,      0], [   764, 507002,     12,      0], [   765, 507002,     17,      0], [   766, 507002,     15,      0], [   767, 104039,      2,      0], [   768, 104039,      3,      0], [   769, 104039,      3,      0], [   770, 104039,      6,      0], [   771, 104039,      6,      0], [   772, 104039,      6,      0], [   773, 104039,      6,      0], [   774, 506912,     18,      0], [   775, 506912,     13,      0], [   776, 506912,     25,      0], [   777, 506912,     25,      0], [   778, 506912,     22,      0], [   779, 506912,     25,      0], [   780, 506912,     21,      0], [   781, 506912,     19,      0], [   782, 104054,      3,      0], [   783, 104054,      3,      0], [   784, 104054,      3,      0], [   785, 506891,      4,      0], [   786, 506891,      4,      0], [   787, 506891,     19,      0], [   788, 506891,      4,      0], [   789, 506891,      4,      0], [   790, 506891,     24,      0], [   791, 506891,     27,      0], [   792, 506891,     20,      0], [   793, 342425,      0,      3], [   794, 342425,     19,      0], [   795, 342425,      5,      0], [   796, 342425,     12,      0], [   797, 104076,     26,      0], [   798, 104076,     13,      0], [   799, 104076,      7,      0], [   800, 104076,     13,      0], [   801, 104076,      4,      0], [   802, 104076,     20,      0], [   803, 104076,      5,      0], [   804, 104076,     14,      0], [   805, 104076,     20,      0], [   806, 104000,     11,      0], [   807, 104000,      3,      0], [   808, 104000,      4,      0], [   815, 342424,     19,      0], [   816, 342424,      4,      0], [   817, 342424,     17,      0], [   818, 342424,      0,     22], [   826, 342426,     24,      0], [   827, 342426,     15,      0], [   828, 342426,      7,      0], [   829, 342426,      5,      0], [   830, 104053,      4,      0], [   831, 104053,      5,      0], [   832, 104053,      5,      0], [   833, 104121,      4,      0], [   834, 104121,      4,      0], [   835, 104121,      4,      0], [   836, 104121,      8,      0], [   837, 104121,      4,      0], [   838, 104121,      4,      0], [   839, 104121,      7,      0], [   840, 104121,      6,      0], [   841, 104121,     10,      0], [   842, 104121,      8,      0], [   843, 104121,     11,      0], [   844, 104121,      2,      0], [   845, 104121,      9,      0], [   846, 104121,      8,      0], [   847, 104121,      4,      0], [   848, 104121,      3,      0], [   849, 506856,      3,      0], [   850, 506856,      2,      0], [   851, 506856,      2,      0], [   852, 342445,     22,      0], [   853, 342445,     22,      0], [   854, 342445,     24,      0], [   855, 342445,     23,      0], [   856, 342445,     20,      0], [   857, 342445,     21,      0], [   858, 506892,      5,      0], [   859, 506892,      6,      0], [   860, 506892,      7,      0], [   861, 506892,      4,      0], [   862, 342423,      2,      0], [   863, 342423,     15,      0], [   864, 342423,     19,      0], [   865, 342423,     20,      0], [   866, 342427,      4,      0], [   867, 342427,      4,      0], [   868, 342427,      7,      0], [   869, 342427,      2,      0], [   870, 342421,     17,      0], [   871, 342421,     10,      0], [   872, 342421,      3,      0], [   873, 342421,      0,     11], [   874, 104056,      2,      0], [   875, 104056,     10,      0], [   876, 104065,     11,      0], [   877, 104065,      4,      0], [   878, 104065,      4,      0], [   879, 104065,      3,      0], [   880, 104065,     13,      0], [   881, 104065,      3,      0], [   882, 104065,      3,      0], [   883, 104065,      3,      0], [   884, 104065,      3,      0], [   885, 104065,      4,      0], [   886, 104065,      3,      0], [   887, 104065,      3,      0], [   888, 104065,      3,      0], [   889, 104065,     14,      0], [   890, 104065,      3,      0], [   891, 104115,      9,      0], [   892, 104115,      9,      0], [   893, 104115,      9,      0], [   894, 104115,     10,      0], [   895, 342429,     20,      0], [   896, 342429,     14,      0], [   897, 342429,     19,      0], [   898, 342429,     16,      0], [   899, 342422,     22,      0], [   900, 342422,     22,      0], [   901, 342422,     17,      0], [   902, 342422,     18,      0], [   903, 104021,      9,      0], [   904, 104021,      9,      0], [   905, 104021,      7,      0], [   906, 104021,      9,      0], [   907, 104021,      3,      0], [   908, 104021,     14,      0], [   909, 104021,     13,      0], [   910, 104021,     15,      0], [   911, 104021,     16,      0], [   912, 342428,     18,      0], [   913, 342428,     21,      0], [   914, 342428,      3,      0], [   915, 104119,      8,      0], [   916, 104119,      3,      0], [   917, 104119,      9,      0], [   918, 104119,      8,      0], [   919, 104119,     11,      0], [   920, 104119,      9,      0], [   921, 104119,     10,      0], [   922, 104119,      0,      5], [   923, 506893,      5,      0], [   924, 506893,     11,      0], [   925, 506893,     16,      0], [   926, 506893,      3,      0], [   927, 506893,      4,      0], [   928, 506893,      3,      0], [   929, 506893,      4,      0], [   930, 506893,      5,      0], [   931, 506893,      4,      0], [   932, 104116,     10,      0], [   933, 104116,     10,      0], [   934, 104116,     12,      0], [   935, 104116,      9,      0], [   936, 104116,      9,      0], [   937, 104116,     13,      0], [   938, 104116,     11,      0], [   939, 104116,     10,      0], [   940, 104116,      3,      0], [   941, 104116,      3,      0], [   942, 104116,      3,      0], [   943, 104116,      4,      0], [   944, 104116,      3,      0], [   945, 507003,      4,      0], [   946, 507003,      4,      0], [   947, 507003,     10,      0], [   948, 507003,     25,      0], [   949, 507003,      5,      0], [   950, 507003,      5,      0], [   951, 507003,      1,      0], [   952, 507003,     34,      0], [   953, 507003,      1,      0], [   954, 507003,      1,      0], [   955, 507003,      1,      0], [   970, 507000,     15,      0], [   971, 104023,     11,      0], [   972, 104023,     11,      0], [   973, 104023,     13,      0], [   974, 104023,      7,      0], [   975, 104023,      7,      0], [   976, 104023,     12,      0], [   977, 104023,     13,      0], [   978, 104023,      3,      0], [   979, 506854,     17,      0], [   980, 506854,     14,      0], [   981, 506854,     18,      0], [   982, 506854,     15,      0], [   983, 506854,     17,      0], [   984, 506854,     14,      0], [   985, 506853,     13,      0], [   986, 506853,     20,      0], [   987, 506853,      9,      0], [   988, 506853,     11,      0], [   989, 506853,      4,      0], [   990, 506853,      9,      0], [   991, 506853,     13,      0], [   992, 506853,      9,      0], [   993, 506853,     19,      0], [   994, 506853,     20,      0], [   995, 506853,      8,      0], [   996, 506853,      8,      0], [   997, 324945,     20,      0], [   998, 324945,     19,      0], [   999, 324945,     13,      0], [  1000, 324945,     44,      0], [  1001, 324945,     17,      0], [  1002, 324945,     25,      0], [  1003, 104110,     14,      0], [  1004, 104110,     12,      0], [  1005, 104110,     14,      0], [  1006, 104110,     15,      0], [  1007, 104110,      6,      0], [  1008, 104110,      6,      0], [  1009, 104110,      7,      0], [  1010, 104110,      5,      0], [  1011, 104110,      5,      0], [  1012, 104110,      5,      0], [  1013, 104110,      5,      0], [  1014, 104110,      3,      0], [  1015, 104111,      9,      0], [  1016, 104111,      9,      0], [  1017, 104036,     17,      0], [  1018, 104036,     13,      0], [  1019, 104036,      3,      0], [  1020, 104036,     13,      0], [  1021, 215628,     20,      0], [  1022, 215628,     20,      0], [  1023, 215628,     18,      0], [  1024, 215628,     18,      0], [  1025, 215628,     21,      0], [  1026, 215628,     20,      0], [  1027, 215628,     19,      0], [  1028, 215628,     22,      0], [  1029, 215628,     18,      0], [  1030, 215628,     21,      0], [  1031, 215628,     25,      0], [  1032, 215628,     21,      0], [  1033, 215628,     21,      0], [  1034, 207983,     18,      0], [  1035, 207983,     20,      0], [  1036, 207983,     18,      0], [  1037, 207983,     23,      0], [  1038, 207983,     23,      0], [  1039, 207983,     23,      0], [  1040, 207983,     18,      0], [  1041, 207983,     24,      0], [  1042, 207983,     22,      0], [  1043, 207983,      2,      0], [  1044, 208020,      7,      0], [  1045, 208020,      2,      0], [  1046, 208020,      0,     11], [  1047, 208020,      0,     19], [  1048, 208015,     21,      0], [  1049, 208015,     14,      0], [  1050, 208015,     20,      0], [  1051, 208015,     13,      0], [  1052, 208015,      2,      0], [  1053, 208015,     18,      0], [  1054, 208015,      2,      0], [  1055, 208015,      2,      0], [  1056, 208015,      0,     31], [  1057, 208015,      0,     25], [  1058, 208015,      0,     31], [  1059, 208015,      0,     25], [  1060, 208015,     11,      0], [  1074, 208019,     22,      0], [  1075, 208019,      2,      0], [  1076, 208019,     18,      0], [  1077, 208019,     17,      0], [  1078, 208019,     18,      0], [  1079, 208019,     21,      0], [  1080, 208018,     22,      0], [  1081, 208018,     16,      0], [  1082, 208018,     16,      0], [  1083, 208018,     18,      0], [  1084, 208018,     15,      0], [  1085, 208018,     23,      0], [  1086, 208018,      0,      5], [  1087, 208018,      0,      6], [  1088, 208018,     13,      0], [  1089, 208017,     19,      0], [  1090, 208017,      7,      0], [  1091, 208021,     16,      0], [  1092, 208021,     16,      0], [  1093, 208021,     20,      0], [  1094, 208021,     15,      0], [  1095, 208021,     18,      0], [  1096, 208021,      1,      0], [  1097, 208021,     15,      0], [  1098, 208021,     10,      0], [  1099, 208021,     24,      0], [  1100, 208021,     18,      0], [  1101, 208021,      2,      0], [  1102, 208021,      3,      0], [  1103, 208021,      2,      0], [  1104, 208021,     17,      0], [  1105, 208021,     12,      0], [  1106, 208021,     14,      0], [  1107, 208021,     17,      0], [  1110, 315272,     23,      0], [  1111, 315272,     18,      0], [  1112, 315272,     12,      0], [  1113, 315272,     13,      0], [  1114, 315272,     23,      0], [  1115, 313879,      3,      0], [  1116, 313879,     17,      0], [  1117, 316220,      8,      0], [  1118, 316220,      8,      0], [  1119, 316220,      8,      0], [  1120, 316220,      4,      0], [  1121, 316220,      9,      0], [  1122, 316220,     22,      0], [  1123, 316220,      2,      0], [  1124, 316220,     14,      0], [  1125, 316220,     23,      0], [  1126, 316220,     20,      0], [  1127, 316220,     23,      0], [  1128, 312797,      3,      0], [  1129, 312797,      7,      0], [  1130, 312797,      3,      0], [  1131, 312797,      6,      0], [  1132, 312797,      4,      0], [  1133, 312797,     12,      0], [  1134, 312797,      4,      0], [  1135, 312797,      4,      0], [  1136, 312797,      2,      0], [  1137, 312797,      6,      0], [  1138, 312797,      4,      0], [  1139, 312797,      3,      0], [  1140, 226868,     17,      0], [  1141, 226868,     19,      0], [  1142, 226868,      4,      0], [  1143, 226868,     19,      0], [  1144, 226868,     15,      0], [  1145, 312799,     14,      0], [  1146, 312799,     17,      0], [  1147, 312799,     20,      0], [  1148, 312799,      2,      0], [  1149, 312799,     16,      0], [  1150, 312799,      3,      0], [  1151, 312799,     12,      0], [  1152, 312799,     10,      0], [  1153, 312799,     11,      0], [  1154, 312799,      4,      0], [  1155, 312799,     11,      0], [  1156, 312799,      0,      4], [  1157, 316377,     30,      0], [  1158, 316377,      8,      0], [  1159, 316377,      4,      0], [  1160, 316377,     39,      0], [  1161, 316377,      3,      0], [  1162, 316377,      7,      0], [  1163, 316221,     11,      0], [  1164, 314490,     18,      0], [  1165, 314490,     22,      0], [  1166, 314490,     19,      0], [  1167, 314490,     21,      0], [  1168, 314490,      7,      0], [  1169, 314490,     21,      0], [  1170, 314490,      2,      0], [  1171, 314490,     16,      0], [  1172, 314490,     11,      0], [  1173, 314489,     20,      0], [  1174, 314489,     21,      0], [  1175, 314489,     22,      0], [  1176, 314489,      8,      0], [  1177, 314489,     16,      0], [  1178, 226833,      2,      0], [  1179, 226833,     23,      0], [  1180, 226833,     14,      0], [  1184, 226832,     14,      0], [  1185, 226832,     13,      0], [  1186, 226832,      0,     20], [  1187, 226832,      0,     21], [  1188, 350037,     15,      0], [  1189, 350037,     19,      0], [  1190, 350037,     28,      0], [  1195, 227387,     17,      0], [  1196, 227387,     16,      0], [  1197, 227387,     12,      0], [  1198, 227387,     11,      0], [  1199, 227387,     11,      0], [  1210, 227386,      6,      0]]


In [5]:
tree_census = np.array(tree_census_list)

In [7]:
# Select all rows of block ID data from the second column
block_ids = tree_census[:,1]

# Print the first five block_ids
print(block_ids[:5])

[501451 501451 501911 501911 501911]


In [8]:
# Select the tenth block ID from block_ids
tenth_block_id = block_ids[9]
print(tenth_block_id)

501911


In [10]:
# Select five block IDs from block_ids starting with the tenth ID
block_id_slice = block_ids[9:14]
print(block_id_slice)

[501911 501911 501911 501909 501909]


## Stepping into 2D
Now our research requires us to take an admittedly unrepresentative sample of trunk diameters, which are located in the third column of tree_census. Getting just a selection of trunk diameters can be done with NumPy's slicing and stepping functionality.

In [15]:
# Create an array of the first 100 trunk diameters from tree_census
hundred_diameters = tree_census[:,2][:100]
print(hundred_diameters)

[24 20  3  3  4  4  4  4  4  3  3  4  2  2  3  4  4  4  0 14  3  4  7  8
  7  8  7  5  6  5  5 17  0 19 21 18  4  5  3  4  3  4 13 13 13  5  4  4
  4 11  5  4  5  8 51  7  4 15  3  8  6  6  3  4  3  2  3  3  6  5  5  5
  5  9  4  4  7  7  6  5  4  4  5  5  5  7  3  5  3  3  6  6  8  7  4  5
  4  4  4  4]


In [17]:
# Create an array of trunk diameters with even row indices from 50 to 100 inclusive
every_other_diameter = tree_census[:,2][50:101:2]
print(every_other_diameter)

[ 5  5 51  4  3  6  3  3  3  6  5  5  4  7  6  4  5  5  3  3  6  8  4  4
  4  6]


## Sorting trees
Sometimes it's easiest to understand data when it is sorted according to the value we are most interested in. We'll create an array containing the trunk diameters in the New York City tree census, sorted in order from smallest to largest.

In [18]:
# Extract trunk diameters information and sort from smallest to largest
sorted_trunk_diameters = np.sort(tree_census[:,2])
print(sorted_trunk_diameters)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5

Notice that the np.sort() function doesn't include an option to sort ascending or descending.

## Filtering with masks
We sorted trees from smallest to largest. Now, we'll use fancy indexing to return the row of data representing the largest tree in tree_census. We'll also examine other trees located on the same block as the largest tree: are they also large?

The tree_census columns in order refer to a tree's ID, its block ID, its trunk diameter, and its stump diameter.

Using Boolean indexing, create an array, largest_tree_data, which contains the row of data on the largest tree in tree_census corresponding to the tree with a diameter of 51.



In [28]:
# Create an array which contains row data on the largest tree in tree_census
largest_tree_data = tree_census[tree_census[:,2] == 51]
print(largest_tree_data)

[[    61 501882     51      0]]


In [22]:
tree_census[0,:]

array([     3, 501451,     24,      0])

In [23]:
[tree_census[:,2] == 51]

[array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
      

In [24]:
tree_census[tree_census[:,2] == 51]

array([[    61, 501882,     51,      0]])

Slice largest_tree_data to retrieve only the block id of the block the largest tree is located on; save this block id as largest_tree_block_id.

In [30]:
# Slice largest_tree_data to get only the block id
largest_tree_block_id = largest_tree_data[0][1]
print(largest_tree_block_id)

501882


Using fancy indexing, create an array called trees_on_largest_tree_block which contains data on all trees with the same block ID as the largest tree.

In [31]:
# Create an array which contains row data on all trees with largest_tree_block_id
trees_on_largest_tree_block = tree_census[tree_census[:,1] == largest_tree_block_id]
print(trees_on_largest_tree_block)

[[    60 501882      8      0]
 [    61 501882     51      0]
 [    62 501882      7      0]
 [    63 501882      4      0]
 [    64 501882     15      0]
 [    65 501882      3      0]
 [    66 501882      8      0]
 [    67 501882      6      0]
 [    68 501882      6      0]
 [    69 501882      3      0]]


So fancy!  Based on our work, it looks like the largest tree on the tree_census is the only really big tree on its block.

## Fancy indexing vs. np.where()
We are double-checking collection data by visiting a few trees in person to confirm their measurements. We've been assigned to check the data for trees on block 313879, and we'd like to make a small array of just the tree data that relates to our work.

As a reminder, the tree_census columns in order refer to a tree's ID, its block ID, its trunk diameter, and its stump diameter.

Using fancy indexing, create an array called block_313879 which only contains data for trees with a block ID of 313879.


In [32]:
# Create the block_313879 array containing trees on block 313879
block_313879 = tree_census[tree_census[:,1] == 313879]
print(block_313879)

[[  1115 313879      3      0]
 [  1116 313879     17      0]]


Using np.where(), create an array of row_indices for trees with a block ID of 313879.

Using row_indices, create block_313879, which contains data for trees on block 313879.

In [37]:
# Create an array of row_indices for trees on block 313879
row_indices = np.where(tree_census == 313879)[0]
row_indices

array([921, 922])

In [38]:
# Create an array which only contains data for trees on block 313879
block_313879 = tree_census[row_indices,:]
print(block_313879)

[[  1115 313879      3      0]
 [  1116 313879     17      0]]


Fancy indexing is more elegant than np.where() in this example. That's because we haven't really tapped into the power of np.where() yet. It's most useful for finding indices and then using that location information to _update_ an array. 

## Creating arrays from conditions
Currently, the stump diameter and trunk diameter values in tree_census are in two different columns. Living trees have a stump diameter of zero while stumps have a trunk diameter of zero. If we'd like to include both living trees and stumps in certain research calculations, it might be useful to have their diameters together in just one column.

 As a reminder, the tree census columns in order refer to a tree's ID, its block ID, its trunk diameter, and its stump diameter.

Create a 1D array called trunk_stump_diameters, which replaces a tree's trunk diameter with its stump diameter if the trunk diameter is zero.

In [39]:
# Create and print a 1D array of tree and stump diameters
trunk_stump_diameters = np.where(tree_census[:,2] == 0,tree_census[:,3], tree_census[:,2] )
print(trunk_stump_diameters)

[24 20  3  3  4  4  4  4  4  3  3  4  2  2  3  4  4  4  3 14  3  4  7  8
  7  8  7  5  6  5  5 17 31 19 21 18  4  5  3  4  3  4 13 13 13  5  4  4
  4 11  5  4  5  8 51  7  4 15  3  8  6  6  3  4  3  2  3  3  6  5  5  5
  5  9  4  4  7  7  6  5  4  4  5  5  5  7  3  5  3  3  6  6  8  7  4  5
  4  4  4  4  6  5  3  4 12 12 12  5  6  6  6  6  6  5  5  6  7  7 25  5
  5  4  6  6  7 11  6 17 13 14 14 20 15 13  7  7 10 17 14  4  6  7  8  7
  7  6  7  5  2  2  2  2 26 25  2 15  6 20  5  9 15 13 15  3  2 13  6 12
 15 18 22 18 18 15 17  7  3  7  8  4 12 11 12  3  9 12 11 10  8  6  6  7
  7  3 15 12 12  4  5  5  5  4  4  5  4  9  2  4  4  6  5  5  2  5  5  4
  4  5  5  6 11  4  5  7  3 14 11 10  7 15 10  5  6 10 10  6  5  4  4  3
  5  4 14 12 11  8 14 12  9 12 11  7  8 10 10 12 11 12  5  5  6  9  9  8
  5  5  5  6  6 12 12 11 12  8  9  5  5  5  8  2  2  2 14 18 14 14 22 15
 19 14 18  7  7  7  8  8  5 10 14  2  2  2  2 11 12 12  3  3  3  3  3  6
  6  8  2  2 11 11 11  9 11 12 13  9 11  6  4  5  5

Looks fantastic! But this is just a 1D array without any tree or block ID information. How do we add this information back to the tree_census array? 

## Adding rows
The research team has discovered two trees that were left off the tree_census. Our task is to add rows containing the data for these new trees to the end of the tree_census array. The new trees' data is saved in a 2D array called new_trees:

In [40]:
new_trees = np.array([[1211, 227386, 20, 0], [1212, 227386, 8, 0]])


Print the shapes of tree_census and new_trees to confirm they are compatible to concatenate.

In [41]:
# Print the shapes of tree_census and new_trees
print(tree_census.shape , new_trees.shape)

(1000, 4) (2, 4)


In [43]:
# Add rows to tree_census which contain data for the new trees
updated_tree_census = np.concatenate((tree_census, new_trees))
print(updated_tree_census)

[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1210 227386      6      0]
 [  1211 227386     20      0]
 [  1212 227386      8      0]]


## Adding columns
We created an array called trunk_stump_diameters, which combined data from the trunk diameter and stump diameter columns into a 1D array. Now, we'll add that 1D array as a column to the tree_census array.

In [44]:
# Print the shapes of tree_census and trunk_stump_diameters
print(tree_census.shape , trunk_stump_diameters.shape)

(1000, 4) (1000,)


Reshape trunk_stump_diameters so that it can be appended as the last column in tree_census; call the reshaped array reshaped_diameters.

In [47]:
# Reshape trunk_stump_diameters
reshaped_diameters = trunk_stump_diameters.reshape((1000,1))

In [50]:
# Concatenate reshaped_diameters to tree_census as the last column
concatenated_tree_census = np.concatenate((tree_census, reshaped_diameters),axis=1)
print(concatenated_tree_census)

[[     3 501451     24      0     24]
 [     4 501451     20      0     20]
 [     7 501911      3      0      3]
 ...
 [  1198 227387     11      0     11]
 [  1199 227387     11      0     11]
 [  1210 227386      6      0      6]]


Adding a 1D array to an existing 2D array requires you to reshape the 1D array into a 2D array first. 

## Deleting with np.delete()
What if our tree research focuses only on living trees on publicly-owned city blocks? It might be helpful to delete some unneeded data like the stump diameter column and some trees located on private blocks.

NumPy's np.delete() function takes three arguments: the original array, the index or indices to be deleted, and the axis to delete along. If we don't know the index or indices of the array we'd like to delete, recall that when it is only passed one argument,np.where() returns an array of indices where a condition is met!

 The columns in order refer to a tree's ID, block number, trunk diameter, and stump diameter.

Delete the stump diameter column from tree_census, and save the new 2D array as tree_census_no_stumps.

Using np.where(), find the indices of any trees on block 313879, a private block. Save the indices in an array called private_block_indices.

In [52]:
# Delete the stump diameter column from tree_census
tree_census_no_stumps = np.delete(tree_census, 3, axis = 1)

# Save the indices of the trees on block 313879
private_block_indices = np.where(tree_census[:,1] == 313879)
private_block_indices

(array([921, 922]),)

In [53]:
# Delete the rows for trees on block 313879 from tree_census_no_stumps
tree_census_clean = np.delete(tree_census_no_stumps, private_block_indices[0], axis = 0)

# Print the shape of tree_census_clean
print(tree_census_clean.shape)
tree_census_clean

(998, 3)


array([[     3, 501451,     24],
       [     4, 501451,     20],
       [     7, 501911,      3],
       ...,
       [  1198, 227387,     11],
       [  1199, 227387,     11],
       [  1210, 227386,      6]])